import type { Document, AccessLogEntry, User, UserRole } from "@/stores/app-store"

export const demoUsers: User[] = [
  { id: "u1", email: "admin@vault.io", name: "System Admin", role: "admin" },
  { id: "u2", email: "editor@vault.io", name: "Content Editor", role: "editor" },
  { id: "u3", email: "viewer@vault.io", name: "External Viewer", role: "viewer" },
]

export const demoDocuments: Document[] = [
  {
    id: "d1",
    title: "Q4 Financial Report",
    type: "document",
    mimeType: "application/pdf",
    size: 2_450_000,
    uploadedAt: "2025-12-01T10:30:00Z",
    expiresAt: "2026-03-01T00:00:00Z",
    uploadedBy: "u1",
    accessRoles: ["admin", "editor"],
    downloadAllowed: true,
    metadata: { pages: 42, department: "Finance" },
  },
  {
    id: "d2",
    title: "Product Demo - v3.0",
    type: "video",
    mimeType: "video/mp4",
    size: 156_000_000,
    uploadedAt: "2025-11-15T14:00:00Z",
    expiresAt: "2026-06-15T00:00:00Z",
    uploadedBy: "u2",
    accessRoles: ["admin", "editor", "viewer"],
    downloadAllowed: false,
    metadata: { duration: "12:34", resolution: "1920x1080" },
  },
  {
    id: "d3",
    title: "Architecture Blueprint",
    type: "image",
    mimeType: "image/png",
    size: 8_700_000,
    uploadedAt: "2026-01-05T09:15:00Z",
    expiresAt: null,
    uploadedBy: "u1",
    accessRoles: ["admin"],
    downloadAllowed: true,
    metadata: { dimensions: "4096x2160" },
  },
  {
    id: "d4",
    title: "Compliance Manual 2026",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 1_200_000,
    uploadedAt: "2026-01-20T11:45:00Z",
    expiresAt: "2027-01-20T00:00:00Z",
    uploadedBy: "u2",
    accessRoles: ["admin", "editor", "viewer"],
    downloadAllowed: true,
    metadata: { pages: 128, version: "2.1" },
  },
  {
    id: "d5",
    title: "Internal Training Video",
    type: "video",
    mimeType: "video/mp4",
    size: 340_000_000,
    uploadedAt: "2026-01-28T08:00:00Z",
    expiresAt: "2026-07-28T00:00:00Z",
    uploadedBy: "u1",
    accessRoles: ["admin", "editor"],
    downloadAllowed: false,
    metadata: { duration: "45:12", resolution: "1920x1080" },
  },
  {
    id: "d6",
    title: "Brand Guidelines",
    type: "document",
    mimeType: "application/pdf",
    size: 5_600_000,
    uploadedAt: "2025-10-10T13:30:00Z",
    expiresAt: null,
    uploadedBy: "u2",
    accessRoles: ["admin", "editor", "viewer"],
    downloadAllowed: true,
    metadata: { pages: 36 },
  },
]

export const demoAccessLogs: AccessLogEntry[] = [
  {
    id: "l1",
    userId: "u3",
    userName: "External Viewer",
    documentId: "d2",
    documentTitle: "Product Demo - v3.0",
    action: "view",
    timestamp: "2026-02-07T15:30:00Z",
    granted: true,
  },
  {
    id: "l2",
    userId: "u3",
    userName: "External Viewer",
    documentId: "d1",
    documentTitle: "Q4 Financial Report",
    action: "view",
    timestamp: "2026-02-07T15:28:00Z",
    granted: false,
  },
  {
    id: "l3",
    userId: "u2",
    userName: "Content Editor",
    documentId: "d4",
    documentTitle: "Compliance Manual 2026",
    action: "download",
    timestamp: "2026-02-07T14:00:00Z",
    granted: true,
  },
  {
    id: "l4",
    userId: "u1",
    userName: "System Admin",
    documentId: "d5",
    documentTitle: "Internal Training Video",
    action: "upload",
    timestamp: "2026-01-28T08:00:00Z",
    granted: true,
  },
  {
    id: "l5",
    userId: "u2",
    userName: "Content Editor",
    documentId: "d6",
    documentTitle: "Brand Guidelines",
    action: "view",
    timestamp: "2026-02-06T09:15:00Z",
    granted: true,
  },
  {
    id: "l6",
    userId: "u3",
    userName: "External Viewer",
    documentId: "d3",
    documentTitle: "Architecture Blueprint",
    action: "download",
    timestamp: "2026-02-05T11:45:00Z",
    granted: false,
  },
  {
    id: "l7",
    userId: "u1",
    userName: "System Admin",
    documentId: "d1",
    documentTitle: "Q4 Financial Report",
    action: "view",
    timestamp: "2026-02-07T16:00:00Z",
    granted: true,
  },
  {
    id: "l8",
    userId: "u2",
    userName: "Content Editor",
    documentId: "d2",
    documentTitle: "Product Demo - v3.0",
    action: "view",
    timestamp: "2026-02-04T10:30:00Z",
    granted: true,
  },
]

export function getStorageStats() {
  const totalStorage = 2_000_000_000
  const usedStorage = demoDocuments.reduce((acc, doc) => acc + doc.size, 0)
  return {
    totalStorage,
    usedStorage,
    freeStorage: totalStorage - usedStorage,
    usagePercent: (usedStorage / totalStorage) * 100,
    documentCount: demoDocuments.length,
    videoCount: demoDocuments.filter((d) => d.type === "video").length,
    docCount: demoDocuments.filter((d) => d.type === "document").length,
    imageCount: demoDocuments.filter((d) => d.type === "image").length,
  }
}
